"""
tb-replay — Replay recorded HDF5 episodes back through AGXUnity.

Usage
-----
    # Single episode
    tb-replay --episode data/agx_teleop/episode_0.hdf5

    # All episodes in a directory (sorted by episode index)
    tb-replay --episode data/agx_teleop_v1/

    # With config and video output
    tb-replay --episode data/agx_teleop_v1/ --config testbed/configs/teleop_v1.yaml --save-video

Purpose
-------
QA check: replay action[t] step-by-step and verify that:
  - qpos/qvel time series are visually consistent with the recording
  - step_id increments match expectations

Outputs (when --save-video)
    runs/replay/<episode_stem>_replay.mp4

Outputs (when --record-output-dir)
    episode_N.hdf5 files regenerated by replaying the source actions through
    the live Unity backend. This is useful after Unity-side observation or
    env_state instrumentation changes. When the teleop config defines
    post_success_tail_steps, replay refresh appends that many zero-action hold
    steps after the source actions so terminal dump observations are not cut
    off.
"""

from __future__ import annotations

import argparse
import logging
import re
import time
from pathlib import Path

import numpy as np
import yaml

log = logging.getLogger(__name__)


def _episode_sort_key(path: Path) -> tuple[int, str]:
    """Sort episode files by numeric index, falling back to name."""
    match = re.search(r"episode_(\d+)", path.stem)
    return (int(match.group(1)), path.stem) if match else (999999, path.stem)


def _resolve_episodes(path: Path) -> list[Path]:
    """Return a sorted list of .hdf5 episode files from a file or directory."""
    if path.is_file():
        return [path]
    if path.is_dir():
        episodes = sorted(path.glob("episode_*.hdf5"), key=_episode_sort_key)
        if not episodes:
            episodes = sorted(path.glob("*.hdf5"), key=_episode_sort_key)
        return episodes
    raise FileNotFoundError(f"Not a file or directory: {path}")


def main() -> None:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    )

    parser = argparse.ArgumentParser(
        prog="tb-replay",
        description="Replay recorded HDF5 episode(s) through AGX and optionally record video.",
    )
    parser.add_argument("--episode", "-e", type=Path, required=True,
                        help="Path to a single episode_N.hdf5 or a directory of episodes.")
    parser.add_argument("--config", "-c", type=Path, default=None,
                        help="Teleop YAML config (for AGX host/port). "
                             "If omitted, uses defaults (localhost:5057).")
    parser.add_argument("--save-video", action="store_true",
                        help="Save fpv frames to an mp4 video file.")
    parser.add_argument("--video-dir", type=Path, default=Path("runs/replay"),
                        help="Output directory for replay videos.")
    parser.add_argument("--realtime", action="store_true",
                        help="Sleep between steps to match original control rate.")
    parser.add_argument("--record-output-dir", type=Path, default=None,
                        help="Optional directory for regenerated HDF5 episodes.")
    parser.add_argument("--post-tail-steps", type=int, default=None,
                        help="Optional zero-action hold steps to append when "
                             "recording regenerated HDF5. Defaults to "
                             "teleop.post_success_tail_steps from --config.")
    args = parser.parse_args()

    episodes = _resolve_episodes(args.episode)
    if not episodes:
        log.error("No .hdf5 episode files found at %s", args.episode)
        return
    log.info("Found %d episode(s) to replay.", len(episodes))

    # ── Load config ───────────────────────────────────────────────────────────
    agx_cfg: dict = {}
    teleop_cfg: dict = {}
    task_cfg: dict = {}
    success_cfg: dict = {}
    reward_cfg: dict = {}
    if args.config:
        with open(args.config) as f:
            cfg = yaml.safe_load(f) or {}
        agx_cfg  = cfg.get("agx", {})
        teleop_cfg = cfg.get("teleop", {})
        task_cfg = cfg.get("task", {})
        success_cfg = cfg.get("success", {})
        reward_cfg = cfg.get("reward", {})
    post_tail_steps = _resolve_post_tail_steps(
        explicit_value=args.post_tail_steps,
        teleop_cfg=teleop_cfg,
        record_output_dir=args.record_output_dir,
    )

    # ── Build backend (shared across all episodes) ────────────────────────────
    from testbed.backends.agx.backend import AGXSimBackend
    from testbed.tasks.logic.excavator_reward import (
        build_agx_excavation_mission_overrides,
    )

    first_meta = _peek_metadata(episodes[0], task_cfg)
    reward_overrides = build_agx_excavation_mission_overrides(
        success_cfg=success_cfg,
        reward_cfg=reward_cfg,
    )
    backend = AGXSimBackend(
        host=agx_cfg.get("host", "127.0.0.1"),
        port=agx_cfg.get("port", 5057),
        timeout=agx_cfg.get("timeout", 10.0),
        reset_terrain=agx_cfg.get("reset_terrain", True),
        reset_pose=agx_cfg.get("reset_pose", True),
        task_name=first_meta["task_name"],
        reward_overrides=reward_overrides,
    )

    # ── Replay each episode ───────────────────────────────────────────────────
    summary: list[dict] = []
    try:
        record_start_idx = (
            _next_episode_idx(args.record_output_dir)
            if args.record_output_dir is not None
            else 0
        )
        for ep_idx, ep_path in enumerate(episodes):
            result = _replay_one(
                backend=backend,
                ep_path=ep_path,
                ep_idx=ep_idx,
                total=len(episodes),
                task_cfg=task_cfg,
                reward_cfg=reward_cfg,
                success_cfg=success_cfg,
                save_video=args.save_video,
                video_dir=args.video_dir,
                realtime=args.realtime,
                record_output_dir=args.record_output_dir,
                record_episode_idx=record_start_idx + ep_idx,
                config_path=args.config,
                post_tail_steps=post_tail_steps,
            )
            summary.append(result)
    finally:
        backend.close()

    # ── Summary ───────────────────────────────────────────────────────────────
    _print_batch_summary(summary)


# ─── Helpers ──────────────────────────────────────────────────────────────────


def _peek_metadata(ep_path: Path, task_cfg: dict) -> dict:
    from testbed.data.hdf5_io import read_episode
    ep = read_episode(ep_path)
    meta = ep.get("metadata", {})
    return {
        "task_name": str(meta.get("task_name", task_cfg.get("task_name", "agx_excavation_teleop"))),
    }


def _replay_one(
    *,
    backend,
    ep_path: Path,
    ep_idx: int,
    total: int,
    task_cfg: dict,
    reward_cfg: dict,
    success_cfg: dict,
    save_video: bool,
    video_dir: Path,
    realtime: bool,
    record_output_dir: Path | None,
    record_episode_idx: int,
    config_path: Path | None,
    post_tail_steps: int,
) -> dict:
    from testbed.data.hdf5_io import read_episode
    from testbed.data.recorder import EpisodeRecorder
    from testbed.planner.boundary_detector import build_boundary_detector_from_config

    ep = read_episode(ep_path)

    actions:  np.ndarray = ep["actions"]
    qpos_ref: np.ndarray = ep["qpos"]
    meta:     dict       = ep.get("metadata", {})
    T = len(actions)

    control_hz = float(meta.get("control_hz", task_cfg.get("control_hz", 50)))
    seed       = int(meta.get("seed", -1))
    scenario_id = str(meta.get("scenario_id", task_cfg.get("scenario_id", ""))).strip()
    scenario_id = scenario_id or None

    log.info(
        "[%d/%d] Episode: %s  T=%d  control_hz=%.0f  seed=%d  scenario_id=%s",
        ep_idx + 1, total, ep_path.name, T, control_hz, seed, scenario_id or "",
    )

    frames: list[np.ndarray] = []
    qpos_replay: list[np.ndarray] = []
    recorder = None
    if record_output_dir is not None:
        info = backend.get_info()
        camera_names = _resolve_camera_names(meta, task_cfg)
        recorder = EpisodeRecorder(
            output_dir=record_output_dir,
            episode_idx=record_episode_idx,
            metadata=_build_replay_metadata(
                source_metadata=meta,
                source_episode=ep_path,
                info=info,
                camera_names=camera_names,
                config_path=config_path,
                post_tail_steps=post_tail_steps,
            ),
            camera_names=camera_names,
        )
        log.info(
            "[%d/%d] Recording regenerated HDF5 episode_%d.hdf5 → %s",
            ep_idx + 1, total, record_episode_idx, record_output_dir,
        )

    boundary_detector = build_boundary_detector_from_config(
        reward_cfg=reward_cfg,
        success_cfg=success_cfg,
    )
    target_dump_count = _metadata_int(meta.get("target_dump_count"), default=0)
    episode_success = False
    ts = backend.reset(seed=seed, scenario_id=scenario_id)

    def _advance(
        *,
        action: np.ndarray,
        record_step_index: int,
        progress_index: int,
        progress_total: int,
        progress_label: str,
        action_src_id: str,
        include_in_qpos_qa: bool,
    ):
        nonlocal ts, episode_success

        obs_before = ts.observation
        if include_in_qpos_qa:
            qpos_replay.append(np.asarray(obs_before["qpos"], dtype=np.float32).copy())

        ts = backend.step(action)
        obs_after = ts.observation
        if recorder is not None:
            recorder.record(
                obs=obs_before,
                action=action,
                reward=ts.reward,
                step_id=int(obs_before.get("step_id", record_step_index)),
                step_ns=time.time_ns(),
                action_src_type="scripted",
                action_src_id=action_src_id,
            )
        episode_success = episode_success or bool(ts.info.get("task_success", False))
        boundary_event = boundary_detector.update(
            env_state=obs_after.get("env_state", np.zeros(13, dtype=np.float32)),
            action=action,
            qpos=obs_after.get("qpos", np.zeros(4, dtype=np.float32)),
            reward_phase=str(ts.info.get("reward_phase", obs_after.get("reward_phase", ""))),
            task_step_successes=list(
                ts.info.get(
                    "task_step_successes",
                    obs_after.get("task_step_successes", []),
                )
            ),
            task_metrics=dict(
                ts.info.get("task_metrics", obs_after.get("task_metrics", {}))
            ),
        )
        if save_video and "fpv" in obs_before["images"] and obs_before["images"]["fpv"] is not None:
            frames.append(obs_before["images"]["fpv"].copy())

        if realtime:
            time.sleep(1.0 / control_hz)

        if (progress_index + 1) % 100 == 0:
            log.info("  %s %d / %d", progress_label, progress_index + 1, progress_total)

        if boundary_event.dump_end:
            log.info(
                "  detected dump_end #%d at replay step %d",
                boundary_detector.completed_dump_count,
                record_step_index + 1,
            )
        return boundary_event

    for t in range(T):
        action = np.asarray(actions[t], dtype=np.float32)
        _advance(
            action=action,
            record_step_index=t,
            progress_index=t,
            progress_total=T,
            progress_label="step",
            action_src_id=f"replay:{ep_path.name}",
            include_in_qpos_qa=True,
        )

    if recorder is not None and post_tail_steps > 0:
        tail_action_dim = int(actions.shape[1]) if actions.ndim == 2 else 4
        tail_action = np.zeros(tail_action_dim, dtype=np.float32)
        log.info(
            "[%d/%d] Appending %d zero-action tail step(s).",
            ep_idx + 1,
            total,
            post_tail_steps,
        )
        for tail_idx in range(post_tail_steps):
            _advance(
                action=tail_action,
                record_step_index=T + tail_idx,
                progress_index=tail_idx,
                progress_total=post_tail_steps,
                progress_label="tail step",
                action_src_id=f"replay_tail:{ep_path.name}",
                include_in_qpos_qa=False,
            )

    qpos_arr = np.stack(qpos_replay)
    min_T = min(len(qpos_ref), len(qpos_arr))
    diff = np.abs(qpos_ref[:min_T] - qpos_arr[:min_T])
    mean_diff, max_diff = float(diff.mean()), float(diff.max())
    log.info(
        "[%d/%d] QA — qpos diff: mean=%.4f  max=%.4f  (%d steps)",
        ep_idx + 1, total, mean_diff, max_diff, min_T,
    )

    if save_video and frames:
        video_dir.mkdir(parents=True, exist_ok=True)
        out_path = video_dir / f"{ep_path.stem}_replay.mp4"
        _save_video(frames, out_path, fps=int(control_hz))
        log.info("[%d/%d] Video saved → %s", ep_idx + 1, total, out_path)

    recorded_path = None
    if recorder is not None and len(recorder) > 0:
        completed_dump_count = int(boundary_detector.completed_dump_count)
        recorder.metadata["completed_dump_count"] = completed_dump_count
        if target_dump_count > 0:
            recorder.metadata["target_dump_count"] = int(target_dump_count)
        if target_dump_count > 0 and completed_dump_count >= target_dump_count:
            recorder.metadata["stop_reason"] = "target_dump_count_reached"
            episode_success = True
        else:
            recorder.metadata["stop_reason"] = "replay_complete"
        recorded_path = recorder.save(success=episode_success)
        log.info("[%d/%d] Regenerated episode saved → %s", ep_idx + 1, total, recorded_path)

    return {
        "episode": ep_path.name,
        "steps": T,
        "recorded_steps": 0 if recorder is None else len(recorder),
        "qpos_mean_diff": mean_diff,
        "qpos_max_diff": max_diff,
        "recorded_episode": "" if recorded_path is None else str(recorded_path),
    }


def _print_batch_summary(summary: list[dict]) -> None:
    if not summary:
        return
    log.info("=" * 60)
    log.info("Batch replay summary: %d episode(s)", len(summary))
    log.info("%-25s %6s %12s %12s", "episode", "steps", "mean_diff", "max_diff")
    for s in summary:
        log.info(
            "%-25s %6d %12.4f %12.4f",
            s["episode"], s["steps"], s["qpos_mean_diff"], s["qpos_max_diff"],
        )
    all_mean = np.mean([s["qpos_mean_diff"] for s in summary])
    all_max  = np.max([s["qpos_max_diff"]  for s in summary])
    log.info("%-25s %6s %12.4f %12.4f", "OVERALL", "", all_mean, all_max)
    log.info("=" * 60)


def _next_episode_idx(output_dir: Path) -> int:
    existing = sorted(output_dir.glob("episode_*.hdf5")) if output_dir.exists() else []
    if not existing:
        return 0

    indices: list[int] = []
    for path in existing:
        match = re.search(r"episode_(\d+)", path.stem)
        if match:
            indices.append(int(match.group(1)))
    return (max(indices) + 1) if indices else 0


def _resolve_post_tail_steps(
    *,
    explicit_value: int | None,
    teleop_cfg: dict,
    record_output_dir: Path | None,
) -> int:
    if record_output_dir is None and explicit_value is None:
        return 0
    value = (
        explicit_value
        if explicit_value is not None
        else teleop_cfg.get("post_success_tail_steps", 0)
    )
    return max(0, int(value))


def _resolve_camera_names(meta: dict, task_cfg: dict) -> list[str]:
    configured = task_cfg.get("camera_names")
    if configured:
        return [str(item) for item in configured]

    raw = meta.get("camera_names", "fpv")
    if isinstance(raw, bytes):
        raw = raw.decode()
    if isinstance(raw, str):
        names = [item.strip() for item in raw.split(",") if item.strip()]
        return names or ["fpv"]
    if isinstance(raw, (list, tuple)):
        return [str(item.decode() if isinstance(item, bytes) else item) for item in raw]
    return ["fpv"]


def _build_replay_metadata(
    *,
    source_metadata: dict,
    source_episode: Path,
    info,
    camera_names: list[str],
    config_path: Path | None,
    post_tail_steps: int,
) -> dict:
    from testbed.data.schema import (
        ATTR_ACTION_ORDER,
        ATTR_ACTION_SEMANTICS,
        ATTR_CAMERA_FPS,
        ATTR_CAMERA_HEIGHT,
        ATTR_CAMERA_NAMES,
        ATTR_CAMERA_ROW_ORDER,
        ATTR_CAMERA_WIDTH,
        ATTR_CONTROL_HZ,
        ATTR_DT,
        ATTR_ENV_STATE_ORDER,
        ATTR_EPISODE_ID,
        ATTR_IMAGE_FORMAT,
        ATTR_PROTOCOL_VERSION,
        ATTR_QPOS_ORDER,
        ATTR_QVEL_ORDER,
        ATTR_REPLAY_CONFIG_PATH,
        ATTR_REPLAY_POST_TAIL_STEPS,
        ATTR_REPLAY_SOURCE_DATASET,
        ATTR_REPLAY_SOURCE_EPISODE,
        ATTR_SIM_BACKEND,
        ATTR_TELEOP_INPUT,
    )

    metadata = dict(source_metadata)
    metadata.pop(ATTR_EPISODE_ID, None)
    metadata.update(
        {
            ATTR_SIM_BACKEND: "agxunity",
            ATTR_CONTROL_HZ: int(round(float(info.control_hz))),
            ATTR_DT: float(info.dt),
            ATTR_ACTION_SEMANTICS: info.action_semantics,
            ATTR_CAMERA_NAMES: ",".join(camera_names),
            ATTR_PROTOCOL_VERSION: info.protocol_version,
            ATTR_ACTION_ORDER: ",".join(info.action_order),
            ATTR_QPOS_ORDER: ",".join(info.qpos_order),
            ATTR_QVEL_ORDER: ",".join(info.qvel_order),
            ATTR_ENV_STATE_ORDER: ",".join(info.env_state_order),
            ATTR_TELEOP_INPUT: "replay",
            ATTR_REPLAY_SOURCE_EPISODE: str(source_episode),
            ATTR_REPLAY_SOURCE_DATASET: str(source_episode.parent),
            ATTR_REPLAY_POST_TAIL_STEPS: int(post_tail_steps),
        }
    )
    if config_path is not None:
        metadata[ATTR_REPLAY_CONFIG_PATH] = str(config_path)

    camera_by_name = {camera.name: camera for camera in info.cameras}
    if camera_names:
        camera = camera_by_name.get(camera_names[0])
        if camera is not None:
            metadata[ATTR_IMAGE_FORMAT] = camera.pixel_format
            metadata[ATTR_CAMERA_WIDTH] = int(camera.width)
            metadata[ATTR_CAMERA_HEIGHT] = int(camera.height)
            metadata[ATTR_CAMERA_FPS] = float(camera.fps)
            metadata[ATTR_CAMERA_ROW_ORDER] = camera.row_order
    return metadata


def _metadata_int(value, *, default: int = 0) -> int:
    if value is None:
        return default
    if isinstance(value, bytes):
        value = value.decode()
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _save_video(frames: list[np.ndarray], path: Path, fps: int = 50) -> None:
    """Write frames as an mp4 using OpenCV."""
    try:
        import cv2
    except ImportError:
        log.error("opencv-python not installed — cannot save video.")
        return

    if not frames:
        return

    h, w = frames[0].shape[:2]
    fourcc = cv2.VideoWriter_fourcc(*"mp4v")
    writer = cv2.VideoWriter(str(path), fourcc, fps, (w, h))
    for frame in frames:
        writer.write(cv2.cvtColor(frame, cv2.COLOR_RGB2BGR))
    writer.release()


if __name__ == "__main__":
    main()
