"""Backend-neutral runtime contracts for primitive planner ticks."""

from testbed.planner.runtime.blackboard import PlannerBlackboard
from testbed.planner.runtime.conditioning import PlannerConditioningState
from testbed.planner.runtime.contracts import (
    PlannerBackend,
    PlannerRuntimeEffect,
    PlannerTickContext,
    PlannerTickResult,
)
from testbed.planner.runtime.effects import (
    APPLY_BOOTSTRAP_TRANSITION_DECISION_EFFECT,
    APPLY_CARRY_TRANSITION_RUNTIME_EFFECT,
    APPLY_DIG_TRANSITION_RUNTIME_PROJECTION_EFFECT,
    APPLY_DUMP_TRANSITION_RUNTIME_EFFECT,
    APPLY_PRE_DIG_ALIGN_OUTCOME_EFFECT,
    APPLY_RETURN_TO_DIG_TRANSITION_RUNTIME_EFFECT,
    LEGACY_FSM_TRANSITION_EFFECT,
)
from testbed.planner.runtime.ports import (
    CarryTransitionRuntime,
    CarryTransitionRuntimeProvider,
    DigTransitionRuntimeProjection,
    DigTransitionRuntimeProvider,
    DumpTransitionRuntime,
    DumpTransitionRuntimeProvider,
    LegacyFsmBackendPorts,
    LegacyFsmBootstrapPorts,
    LegacyFsmDigTransitionPorts,
    LegacyFsmDumpLifecyclePorts,
    LegacyFsmPreDigAlignmentPorts,
    LegacyFsmReturnTransitionPorts,
    LegacyFsmSkillNames,
    PlannerBackendPorts,
    PlannerDigTransitionPorts,
    PlannerDumpLifecyclePorts,
    PlannerReturnTransitionPorts,
    PlannerSkillNames,
    ReturnTransitionRuntime,
    ReturnTransitionRuntimeProvider,
)
from testbed.planner.runtime.behavior_tree import (
    BEHAVIOR_TREE_EXPERIMENTAL_BACKEND_NAME,
    BehaviorTreeBackend,
)
from testbed.planner.runtime.legacy_fsm import (
    BootstrapTransitionDecisionApplier,
    CarryTransitionRuntimeApplier,
    DigTransitionRuntimeProjectionApplier,
    DumpTransitionRuntimeApplier,
    LegacyStateMachineBackend,
    LegacyFsmTransitionRunner,
    PreDigAlignOutcomeApplier,
    ReturnToDigTransitionRuntimeApplier,
    apply_legacy_fsm_runtime_effects,
)

__all__ = [
    "APPLY_BOOTSTRAP_TRANSITION_DECISION_EFFECT",
    "APPLY_CARRY_TRANSITION_RUNTIME_EFFECT",
    "APPLY_DIG_TRANSITION_RUNTIME_PROJECTION_EFFECT",
    "APPLY_DUMP_TRANSITION_RUNTIME_EFFECT",
    "APPLY_PRE_DIG_ALIGN_OUTCOME_EFFECT",
    "APPLY_RETURN_TO_DIG_TRANSITION_RUNTIME_EFFECT",
    "BEHAVIOR_TREE_EXPERIMENTAL_BACKEND_NAME",
    "BehaviorTreeBackend",
    "BootstrapTransitionDecisionApplier",
    "CarryTransitionRuntimeApplier",
    "CarryTransitionRuntime",
    "CarryTransitionRuntimeProvider",
    "DigTransitionRuntimeProjection",
    "DigTransitionRuntimeProvider",
    "DigTransitionRuntimeProjectionApplier",
    "DumpTransitionRuntimeApplier",
    "DumpTransitionRuntime",
    "DumpTransitionRuntimeProvider",
    "LEGACY_FSM_TRANSITION_EFFECT",
    "LegacyFsmTransitionRunner",
    "LegacyFsmBackendPorts",
    "LegacyFsmBootstrapPorts",
    "LegacyFsmDigTransitionPorts",
    "LegacyFsmDumpLifecyclePorts",
    "LegacyFsmPreDigAlignmentPorts",
    "LegacyFsmReturnTransitionPorts",
    "LegacyFsmSkillNames",
    "LegacyStateMachineBackend",
    "PreDigAlignOutcomeApplier",
    "PlannerBlackboard",
    "PlannerBackend",
    "PlannerBackendPorts",
    "PlannerConditioningState",
    "PlannerDigTransitionPorts",
    "PlannerDumpLifecyclePorts",
    "PlannerReturnTransitionPorts",
    "PlannerSkillNames",
    "PlannerRuntimeEffect",
    "PlannerTickContext",
    "PlannerTickResult",
    "ReturnTransitionRuntime",
    "ReturnTransitionRuntimeProvider",
    "ReturnToDigTransitionRuntimeApplier",
    "apply_legacy_fsm_runtime_effects",
]
